/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 08ffba101536b4f2d62dbfa321eea7b6)
interface __BaseEnv_Env {
	AI: Ai;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
